apiVersion: v1
kind: Service
metadata:
  name: {{ include "sei.fullname" . }}-app
  labels:
    io.kompose.service: app
  {{- include "sei.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
spec:
  type: {{ .Values.app.type }}
  selector:
    io.kompose.service: app
  {{- include "sei.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.app.ports | toYaml | nindent 2 -}}