{{- if .Values.ingress.enabled -}}
{{- $fullName := include "sei.fullname" . -}}
{{- $svcPort := (index .Values.app.ports 0).port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "sei.labels" . | nindent 4 }}
  annotations:
  {{- if contains "alb" .Values.ingress.className }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.alb.scheme }}
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: {{ .Values.ingress.alb.backendProtocol }}
    alb.ingress.kubernetes.io/healthcheck-path: "/sei/Icone.php"
    alb.ingress.kubernetes.io/healthcheck-protocol: "HTTP"
    alb.ingress.kubernetes.io/healthcheck-port: "80"
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.localEnv.appHost }}
    {{- if .Values.ingress.alb.wafv2AclArn }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.ingress.alb.wafv2AclArn | quote }}
    {{- end }} 
    alb.ingress.kubernetes.io/listen-ports: "[{\"HTTPS\":443}, {\"HTTP\":80}]"
    {{- if .Values.ingress.alb.certificateArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.alb.certificateArn | quote }}
    {{- end }} 
    alb.ingress.kubernetes.io/actions.sei-redirection: '{"Type":"redirect","RedirectConfig": {"Host":"{{ .Values.localEnv.appHost }}","Path":"/sei","Port":"443","Protocol":"HTTPS","Query":"#{query}","StatusCode":"HTTP_301"}}'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.alb.groupName | quote }}
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.type=app_cookie,stickiness.app_cookie.cookie_name=PHPSESSID
    alb.ingress.kubernetes.io/auth-session-cookie: PHPSESSID
  {{- end }} 
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.localEnv.appHost }}
#   secretName: tlssecret
  {{- end }}
  rules:
  - host: {{ .Values.localEnv.appHost }}
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: sei-redirection
            port:
              name: use-annotation
      - path: /sei/
        pathType: Prefix
        backend:
          service:
            name: {{ include "sei.fullname" . }}-app
            port: 
              name: {{ (index .Values.app.ports 1).name }}
      - path: /sip/
        pathType: Prefix
        backend:
          service:
            name: {{ include "sei.fullname" . }}-app
            port: 
              name: {{ (index .Values.app.ports 1).name }}
      - path: /infra_js/
        pathType: Prefix
        backend:
          service:
            name: {{ include "sei.fullname" . }}-app
            port: 
              name: {{ (index .Values.app.ports 1).name }}
      - path: /infra_css/
        pathType: Prefix
        backend:
          service:
            name: {{ include "sei.fullname" . }}-app
            port: 
              name: {{ (index .Values.app.ports 1).name }}
{{- end }}