{{- if .Values.jod.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sei.fullname" . }}-jod
  labels:
    io.kompose.service: jod
  {{- include "sei.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.jod.replicas }}
  selector:
    matchLabels:
      io.kompose.service: jod
    {{- include "sei.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.kompose.network/docker-sei-default: "true"
        io.kompose.service: jod
      {{- include "sei.selectorLabels" . | nindent 8 }}
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.jod.image.repository }}:{{ .Values.jod.image.tag | default .Chart.AppVersion }}
        name: jod
        resources: {}
      restartPolicy: Always
{{- end }}