app:
  image:
    repository: registry.laboratory.aws/sei-app
    tag: 4.0.9
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  - name: "https"
    port: 443
    targetPort: 443
  replicas: 1
  type: ClusterIP
  agendador:
    schedule: "* * * * *"
    concurrencyPolicy: Forbid
    failedJobsHistoryLimit: 3
    successfulJobsHistoryLimit: 1

jod:
  enabled: false
  image:
    repository: processoeletronico/jod
    tag: latest
  replicas: 1

ingress:
  enabled: true
  className: "alb"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls: false
  alb:
    scheme: internet-facing # internet-facing/internal
    backendProtocol: HTTPS # HTTP/HTTPS
    wafv2AclArn: ""
    certificateArn: ""
    groupName: "lb-sei"


kubernetesClusterDomain: cluster.local
localEnv:
  appDbHost: sei-postgresql
  appDbPorta: "5432"
  appDbRootPassword: P@ssword
  appDbRootUsername: postgres
  appDbSeiBase: sei
  appDbSeiPassword: sei_user
  appDbSeiUsername: sei_user
  appDbSipBase: sip
  appDbSipPassword: sip_user
  appDbSipUsername: sip_user
  appDbTipo: PostgreSql
  appFontesGitCheckout: ""
  appFontesGitPath: ""
  appFontesGitPrivkeyBase64: ""
  appHost: sei.orgao.br
  appMailAutenticar: ""
  appMailCodificacao: 8bit
  appMailMaxdestinatarios: "999"
  appMailMaxtamanhoanexosmb: "999"
  appMailPorta: "25"
  appMailProtegido: ""
  appMailSeguranca: ""
  appMailSenha: ""
  appMailServidor: mail
  appMailTipo: "2"
  appMailUsuario: ""
  appMemcachedHost: sei-memcached
  appNomecomplemento: SEI - PEN - DTH
  appOrgao: ME
  appOrgaoDescricao: Orgao Processo Eletronico
  appProtocolo: https
  appSeiChaveAcesso: 7babf862e12bd48f3101075c399040303d94a493c7ce9306470f719bb453e0428c6135dc
  appSipChaveAcesso: d27791b894028d9e7fa34887ad6f0c9a2c559cccda5f64f4e108e3573d5db862b66fb933
  appSolrCoreBaseconhecimento: sei-bases-conhecimento
  appSolrCoreProtocolos: sei-protocolos
  appSolrCorePublicacoes: sei-publicacoes
  appSolrTempoCommitBaseconhecimento: "60"
  appSolrTempoCommitProtocolos: "300"
  appSolrTempoCommitPublicacoes: "60"
  appSolrUrl: http://solr:8983/solr
  moduloAssinaturavancadaClientid: assinaturaAvancadaXXX
  moduloAssinaturavancadaInstalar: "false"
  moduloAssinaturavancadaSecret: XXX
  moduloAssinaturavancadaUrlServicos: assinatura-api.staging.iti.br/externo/v2
  moduloAssinaturavancadaUrlprovider: https://cas.staging.iti.br/oauth2.0
  moduloAssinaturavancadaVersao: master
  moduloEstatisticasChave: seipublico
  moduloEstatisticasInstalar: "true"
  moduloEstatisticasSigla: SEIPUBLICO
  moduloEstatisticasUrl: https://estatistica.dev.processoeletronico.gov.br
  moduloEstatisticasVersao: master
  moduloGestaodocumentalInstalar: "false"
  moduloGestaodocumentalVersao: master
  moduloIncomInclusaopublicacao: S
  moduloIncomInstalar: "false"
  moduloIncomPassws: XXX
  moduloIncomSerieid: "10"
  moduloIncomSiorg: "235876"
  moduloIncomUrlws: https://seiwsincom2.in.gov.br/seiwsincom/services/servicoIN?wsdl
  moduloIncomUserws: XXX
  moduloIncomVeiculoid: "2"
  moduloIncomVersao: v1.0.4
  moduloLoginunicoCientidvalidacao: sei.xxx.nuvem.gov.br/validacaosenha
  moduloLoginunicoClientid: sistemas/homologacao/sei/controlador_externo
  moduloLoginunicoInstalar: "false"
  moduloLoginunicoOrgao: "0"
  moduloLoginunicoRedirecturl: http://sei.xxx.nuvem.gov.br/sei/modulos/loginunico/controlador_loginunico.php
  moduloLoginunicoScope: openid+email+phone+profile+govbr_empresa+govbr_confiabilidades
  moduloLoginunicoSecret: XXXX
  moduloLoginunicoSecretvalidacao: XXX
  moduloLoginunicoUrllogout: http://sei.xxx.nuvem.gov.br/sei/modulos/loginunico/logout.php
  moduloLoginunicoUrlprovider: https://sso.staging.acesso.gov.br/
  moduloLoginunicoUrlrevalidacao: https://oauth.staging.acesso.gov.br/v1/
  moduloLoginunicoUrlservicos: https://api.staging.acesso.gov.br/
  moduloLoginunicoVersao: master
  moduloPenCertificadoBase64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR4akNDQXE2Z0F3SUJBZ0lDRURBd0RRWUpLb1pJaHZjTkFRRUxCUUF3Y3pFTE1Ba0dBMVVFQmhNQ1FsSXgKR1RBWEJnTlZCQWdNRUVScGMzUnlhWFJ2SUVabFpHVnlZV3d4RVRBUEJnTlZCQWNNQ0VKeVlYTnBiR2xoTVFzdwpDUVlEVlFRS0RBSk5VREVNTUFvR0ExVUVDd3dEVUVWT01Sc3dHUVlEVlFRRERCSkpiblJsY205d1pYSmhZbWxzCmFXUmhaR1V3SGhjTk1UZ3dOekF5TVRVMU16VXpXaGNOTWpnd05qSTVNVFUxTXpVeldqQmNNUXN3Q1FZRFZRUUcKRXdKQ1VqRVpNQmNHQTFVRUNBd1FSR2x6ZEhKcGRHOGdSbVZrWlhKaGJERWNNQm9HQTFVRUNnd1RSR1ZtWVhWcwpkQ0JEYjIxd1lXNTVJRXgwWkRFVU1CSUdBMVVFQXd3TFZGTkZMVWhQVFU5TVQwY3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRHo2L1ZOZHE2aTVzNTRUMzhWMW4xeGZXVWpieXhMS25vY3V2S1UKd0pkSklwMHFiZWZEN2pxSVo2UHF1UG1QaWVVQWcyWHlGUzlzdWlVeFpYYTh0Nkg4SE5hY3FtcWRHRWplOTFpNgoxWTZXTEVPYWtWZkc0a2R0RGdFbkNJMDJjbkpDSE5DWWE0SGVyNzR3eEZUVE5GVUpXU1pWYytiZE1pc1VxYzU1ClUva3dLTWcybHlmVEZ3b2dQS0ZOOXZ2bGJCTjR2bmVnTjl2Y3ZDNWprVXF5RjZxZkR0QmpOYjRHZVFINjBZT1AKVWpaRUc3UGtRWGJ0OXBPL2F3MmQvU0gxVFR4ODBCM0RGeWJBdFp4MHdTNzRtWDdYeC9oWXFrOU9NUkxQcmoxUwpEQTNtZEtKY0hpTTF2dUNPSXFlbnk5cCszWk9hV1BiVEpVcU5UWmdySDBCemdSbXpBZ01CQUFHamV6QjVNQWtHCkExVWRFd1FDTUFBd0xBWUpZSVpJQVliNFFnRU5CQjhXSFU5d1pXNVRVMHdnUjJWdVpYSmhkR1ZrSUVObGNuUnAKWm1sallYUmxNQjBHQTFVZERnUVdCQlRqM2NlZ01hWFlWU3pIL3dhdDhaamQ1UGtJempBZkJnTlZIU01FR0RBVwpnQlNZM2ZqdXU5TnhPT05oK2FRZXE1T2pZQzN0dXpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUt5OFFTSkswCmRmV0VlSHU2Y1ZWdTBrSmo3SGZRd1QwcGkzNkhBOWNsV3dvY2RidWRkR2NHS2JXOHJSVU1DM3h3VzJ2bHlRekoKL0RCN0p4eEphVFZycG5iMVhMRlM3ZHhCbmN0dUd1ZWMrRUNVamg5VDA1VCtTbVVmQ3I1bHBMUnR0bTBiWFlmRgpJMWVjNy90ZitQTEJMbFBMSXhvMXNoWHd4T3d0eHFUcUtMRSt0VkNPNlBUY2NON1ZsQXJTcXZ5T2NYMGE1RFpBCitIUkh1RVdkKzdUWnZJdXhHSTlMYjFDMm5GRkt1WVRMYTczOFE2QWZxT2RlS0VWUWtaMi9HNHFLdGJlK0R5L2IKK2tJK2UxTmZwSTlmQm9nK2hhWnZjZGMrajY3MmFCNWhNOTd0OHJ4ZzVFYVZLV3RIbkJFVGd6WlhLQVZHWE1PdwpsazdYd0VaTU5PRUtMQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV3QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktvd2dnU21BZ0VBQW9JQkFRRHo2L1ZOZHE2aTVzNTQKVDM4VjFuMXhmV1VqYnl4TEtub2N1dktVd0pkSklwMHFiZWZEN2pxSVo2UHF1UG1QaWVVQWcyWHlGUzlzdWlVeApaWGE4dDZIOEhOYWNxbXFkR0VqZTkxaTYxWTZXTEVPYWtWZkc0a2R0RGdFbkNJMDJjbkpDSE5DWWE0SGVyNzR3CnhGVFRORlVKV1NaVmMrYmRNaXNVcWM1NVUva3dLTWcybHlmVEZ3b2dQS0ZOOXZ2bGJCTjR2bmVnTjl2Y3ZDNWoKa1VxeUY2cWZEdEJqTmI0R2VRSDYwWU9QVWpaRUc3UGtRWGJ0OXBPL2F3MmQvU0gxVFR4ODBCM0RGeWJBdFp4MAp3Uzc0bVg3WHgvaFlxazlPTVJMUHJqMVNEQTNtZEtKY0hpTTF2dUNPSXFlbnk5cCszWk9hV1BiVEpVcU5UWmdyCkgwQnpnUm16QWdNQkFBRUNnZ0VCQUs5T0RUM0FKMkRpbXM5eTZ2Wko4bHduY0JIWWE3QVY5aTlCMk9nNXhrRUUKeEluaTlXZ21oaURVdzhVRmJpN1FQeXB3UlV1SUdFNS9OZzNiUzB2MGVsSFVkQldpa1A4WW5mN0pMQmNUTnVnTgpKZ1Vub2p0SkUyWjRZekduZnIzNzRNeE5JMG40TWgxV2wwMDdQVytScy9BRkIzencwS0oyMU9tRDVPWGtDVHFuCkhaTy9yUkw2UlFGaVRBeGdUQjZlVjZsclhsVHJkWEFMUGdMcmdBREErMTNjUldtZXNNL3JZWUdCWkpUdjVhVHQKNXRHZm00WWljUExlTHg3QzNmQ0Y0WlN1VEkrbmhPbjlCNXhMdmxicmdMeG1PTGV2eXZXWDREZkFNS3lYWjM1dwp4MUc1djNLaU9zcjYyczZHUG1na1V4QjI5enNmUDhyZnJDSXl2T05RcHdrQ2dZRUEreUtEM05PcmlEcVM0bmdjCjVVWUtSU0EyUlU4Wjd3TDFzYWlhcEFDT3JkYm5yL041OFNJVTBMUG02UnIxeXliYUY1Z3VOQURSZWhtN0ROZnEKT1hJUzNNT0tQOXkvNzdpdnBsMitwM3BYQnYxbU5xTWQ5T1JhNUFmcCtUNFpoUzVsbHZXV3V0b0VvRTdlaFQ4Kwo1akRFYUl6amdRVnBqd0xZdkhBeDJrYUJ4KzBDZ1lFQStLV3JrMHJSMHVTdTM3VnpnNUNVWm03U1FjaWV4aHM2CkZqQzMzQW0wTDJmT2FGbG4wSHlsQTlRL0lxcitDTVErQWlkd3JmdkZZeG51N2xhTGl1VlZSREVWNW9Vbm13ZU8KWVRoTnRiOTdaeXhWUFNzcXh6cGd4TWZ6QVhkVzAvbUFiWlZYWWNUVUVNVW9NdklJSzBlQVpCblFEZmNNYncvKwp2Sk9rbHZTczlCOENnWUVBcTVObU1hM3Y2Ry9VUUtPOVlpc2JBeVZCenRKL0xsdUFUdk9aUzJrU0VkVGNqOHF4CnlqdjFxcXp1bXQ0UGhjOHllNkkrRnN0a1VwNVh2Q3ViMjhtQzk0OGsyZ0xRbzFBenVWOGN6Y0Y0eWM3QVVaM1oKN3FGQk03L3dhNWV3eWR2c0Rsb1ZzKzBWOGd4UVhRcmJ4MXNVSlRYMGpRYU1tdWRmK2taUTJRY0l6ZlVDZ1lFQQowTW1VZkJjc2Y1RWxRcFpFRENyQVlnOFdvTVNNaGo5Z2xEZU9lOGJ1Tll4T0p4TkQrQzVpQmdnWWg4emJpWkwzCm1xbHhsYmEvTllzV05hNFllS1kvNWdYdHBPY1VyYm8zbFcxSTI1K1JTTDVTU1EzUld2K3JPREhKM09aUDA2bEQKYlVFazRlVDhTYVMwTDZ0S3JzVFlpN1dkSGN6ZjlQYVNhZGowTVFuOW5QTUNnWUVBMTBmallOT2krYWsvZ29NeQpvUnZXZEhlUkJ0SDBGcElLWUN6L1BrTTBPYWNMdDdUY29ldm04WXpESUpyTHprd3NtejFSV2pic3VGSlEyeEJhCkxwTkxIRk5Jc3NvbnhtRFVHOWdCekNMU25kbTlIK3JsS0tFTFJhYzREeVE5bUNxYmFDZlVRblpxYmpMQXJ0WTUKekY2UmRJUHRidzV4ZmNoczJHYk9Lb2JDWmc4PQotLS0tXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  moduloPenCertificadoSenha: "1234"
  moduloPenGearmanIp: ""
  moduloPenGearmanPorta: ""
  moduloPenInstalar: "true"
  moduloPenQtdWorkerProc: "1"
  moduloPenRepositorioOrigem: ""
  moduloPenTipoProcessoExterno: ""
  moduloPenUnidadeAssociacaoPen: ""
  moduloPenUnidadeAssociacaoSei: ""
  moduloPenUnidadeGeradora: ""
  moduloPenVersao: master
  moduloPenWebservice: https://homolog.api.processoeletronico.gov.br/interoperabilidade/soap/v3/
  moduloPeticionamentoInstalar: "true"
  moduloPeticionamentoUrl: https://github.com/anatelgovbr/mod-sei-peticionamento
  moduloPeticionamentoVersao: v4.0.3
  moduloPiEmail: email@example.com
  moduloPiInstalar: "false"
  moduloPiSenha: senhadeconexaoaopi
  moduloPiUrl: https://protocolointegrado.preprod.nuvem.gov.br/ProtocoloWS/integradorService?wsdl
  moduloPiUsuario: usuariodeconexaopi
  moduloPiVersao: master
  moduloRespostaDocumentoId: ""
  moduloRespostaInstalar: "false"
  moduloRespostaSistemaId: ""
  moduloRespostaVersao: master
  moduloRestChave: ""
  moduloRestIdApp: ""
  moduloRestInstalar: "false"
  moduloRestTokenSecret: ""
  moduloRestUrlNotificacao: ""
  moduloRestVersao: master
  openldapAdminPassword: adminldap
  openldapDesligarNoOrgao0: "false"
  openldapPresente: "false"
  servicoPdInstalar: "false"
  servicoPdNome: Protocolo.GOV.BR
  servicoPdOperacoes: 3,2,15,0,1
  servicoPdSigla: GOV.BR
  sipEmailAdministrador: admin@dominio.local
  sipEmailSistema: noreply@dominio.local

pvc:
  # Volume de arquivos externos precisa ser ReadWriteMany
  arquivosexternosStorage:
    storageRequest: 1Gi
    storageClass: s3-storage-class
    s3Storage:
      region: sa-east-1
      bucketName: sei-arquivos-externos

# Postgresql database configuration
postgresql: 
  enabled: true
  image:
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
  persistence:
    enabled: true
    size: 8Gi
  auth:
    postgresPassword: P@ssword
    username: sei_user
    password: sei_user
    database: sei
  primary:
    extraEnvVars:
      - name: PGDATESTYLE
        value: "ISO, DMY"
      - name: PGCLIENTENCODING
        value: "Latin1"
  resources:
    requests:
      cpu: 100m
      memory: 64Mi

# Memcached configuration
memcached:
  enabled: true
  architecture: high-availability
  persistence:
    enabled: true
    storageClass: ""
    accessModes: 
      - ReadWriteOnce
    size: 8Gi

# Solr configuration
solr:
  enabled: true
  replicas: 3
  persistence:
    reclaimPolicy: Retain
    size: "50Gi"
  image:
    tag: 8.11.3
  javaMem: "-Xms2g -Xmx2g"
  gcTune: "-XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8"
  tolerations: []
  nodeSelector: {}
  resources:
    limits:
      memory: "6G"
    requests:
      cpu: "650m"
      memory: "1Gi"
  zookeeper:
    persistence:
      size: "5Gi"
    replicas: 3
    tolerations: []
    nodeSelector: {}
    resources:
      limits:
        memory: "1G"
      requests:
        cpu: "65m"
        memory: "156Mi"
   